# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sels.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selsDialog(QtWidgets.QDialog):
    def __init__(self, parent = None):
        super(Ui_selsDialog, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("selsDialog")
        self.resize(720, 380)
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(0, 0, 720, 60))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.298507 rgba(83, 97, 142, 255), stop:1 rgba(97, 69, 128, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabWidget = QtWidgets.QTabWidget(self)
        self.tabWidget.setGeometry(QtCore.QRect(0, 60, 720, 250))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 720, 220))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 720, 220))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 720, 220))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        self.frame_2 = QtWidgets.QFrame(self)
        self.frame_2.setGeometry(QtCore.QRect(0, 310, 720, 70))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.298507 rgba(83, 97, 142, 255), stop:1 rgba(97, 69, 128, 255));")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("selsDialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("selsDialog", "COD"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("selsDialog", "Titulo"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("selsDialog", "P.U"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("selsDialog", "CNT"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("selsDialog", "P.V."))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("selsDialog", "Hora"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("selsDialog", "Boleta"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("selsDialog", "User"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("selsDialog", "Day"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("selsDialog", "Day1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("selsDialog", "Day2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    selsDialog = QtWidgets.QDialog()
    ui = Ui_selsDialog(selsDialog)
    #ui.setupUi(selsDialog)
    selsDialog.show()
    sys.exit(app.exec_())
